[project]
name = "spotify-organiser"
version = "0.1.0"
description = "A Flask web app to sort Spotify playlists by genre"
authors = [
  { name = "KshKnsl", email = "kushkansal0@gmail.com" }
]
requires-python = ">=3.9"

dependencies = [
  "spotipy",
  "flask",
  "python-dotenv",
  "pandas"
]
